### ISSUE TITLE
logo design Proposal 

### ISSUE THREAD

**Issue by Pelikens** [WebBreacher/osintprocess#3]
Hello! I want to contribute on your project with making free logo design. What do you think about it?

Best Regards,
Ksenia
Graphics Designer

**Comment by WebBreacher** [comment]
That'd be really neat!

**Comment by Pelikens** [comment]
Hi and thanks for your reply! That's great! Do you have any special requirements for the logo? Any symbols that should be included? And how do you plan to use the logo? On your web site and etc?

**Comment by WebBreacher** [comment]
Usage would be on digital media, web site, I'm giving a talk at the Defcon conference in August and I could use it in the slides if it is ready by then.

YOGA is about connecting related pieces of OSINT data. That is all I have for creativity right now.

**Comment by Pelikens** [comment]
ok, I'll try to offer you an option tomorrow.

**Comment by Pelikens** [comment]
Hi, here is an option for the logo. I wanted it to be relevant to Yoga and to your project with nodes, edges and arrows.  Please, let me know what do you think?

**Comment by Pelikens** [comment]
![image](https://user-images.githubusercontent.com/39441298/43135393-f54672da-8f4d-11e8-81be-ea3e979e2315.png)

**Comment by WebBreacher** [comment]
I like the graphic but not the yellowish color. do you have other choices
for the colors?

**Comment by Pelikens** [comment]
no problem, maybe so? 
![image](https://user-images.githubusercontent.com/39441298/43138237-d9b75a08-8f56-11e8-8e92-1777d7a76792.png)

**Comment by WebBreacher** [comment]
I like #4

**Comment by Pelikens** [comment]
Ok.  I'll open the PR when I make you options of all sizes, color and monochrome

**Comment by Pelikens** [comment]
I uploaded all the required files and created a pull-request. Please merge it if everything is Ok
