### ISSUE TITLE
More groups, more colors

### ISSUE THREAD

**Issue by nickbash11** [WebBreacher/osintprocess#5]
Hi, I liked this project.
How can I add more colors for nodes?

**Comment by WebBreacher** [comment]
Really simple. Just change the `group: 3` at the end of an entry in the NODES section to another number. Each number (4, 5, 6, ...) will have a different color.

**Comment by nickbash11** [comment]
Oops, sorry. I've tried before and have no success, seems doing something wrong. Thanks!
